### ISSUE TITLE
Github Project Request: Bug Reporting Template for Issue Submissions

### ISSUE THREAD

**Issue by jan-kleks** [SmokeMonsterPacks/Super-NT-Jailbreak#12]
[Create an issue template for this repository](https://help.github.com/articles/creating-an-issue-template-for-your-repository/).

In the case of your project this could contain questions such as "whether the game was tested with original hardware as well?", "what kind of ROM was used (provide the checksum)?", the questions about most important Super Nt settings, etc.

Consult this with the dev behind the jailbroken firmware to see what other question would be useful.

**Comment by frederic-mahe** [comment]
There is now an issue template file automatically loaded when opening a new issue. Suggestions on how to improve it are welcomed.

**Comment by SmokeMonsterPacks** [comment]
Well done, Frederic. It looks like the new form is really working well.  going to close this to keep things tidy.

**Comment by jan-kleks** [comment]
@frederic-mahe @SmokeMonsterPacks [The article about testing games with the Super Nt for bugs has appeared on the Nerdly Pleasures blog](https://nerdlypleasures.blogspot.com/2018/02/super-nt-testing-and-capturing.html), maybe it will give you some more ideas on how to expand the template.

**Comment by SmokeMonsterPacks** [comment]
That is an excellent article and it's great to know that greathierophant is working on bugs. He will make swift work of them and can provide the technical explanation of why they happen. He helped me burn though hundreds of issues with the NT Mini Pack over the last year.

That said, I think we can keep the template more general in order to get a wider range of bugs. Then more technical users can hash then out following nerdlypleasure's guidelines. I fear that if we get too specific it could isolate people.
