### ISSUE TITLE
SD card browser gets stuck when opening directory

### ISSUE THREAD

**Issue by mankeli** [SmokeMonsterPacks/Super-NT-Jailbreak#147]
SD card browser seems to get stuck when entering SPC directory with 1523 files.
Game keeps running, cursor flashes but no input is read anymore.

**Comment by rykerrk** [comment]
Maybe it's because there's 1523 files in one directory.

**Comment by mankeli** [comment]
@rykerrk your comment doesn't really add any value, this is a bug report

**Comment by rykerrk** [comment]
It's not a valid bug because you're not following the introductory notes on using the SD file browser.  I'll google this for you I guess:

*The maximum number of files (ROMs and subfolders) that can be placed in a given folder is around 300-500, depending on the length of the filenames.

Don't dump the entire Internet onto one directory and you'll probably find it works much better.

**Comment by frederic-mahe** [comment]
Thanks @rykerrk . @mankeli please try to spread your files over several folders. Hopefully, it should fix the issue.

**Comment by mankeli** [comment]
@rykerrk sure, but whether it is or is not a bug report in your eyes, you are still an arrogant little prick.

Anyway, sorry for noise! Missed that bit from the readme. (already spread my files of course..) I guess tho it could say when it's overflowing, but can't have everything.

**Comment by frederic-mahe** [comment]
Let's keep it civil here. Thanks for everybody's input, I am closing the issue.
