### ISSUE TITLE
Improvement: HDMI CEC Support

### ISSUE THREAD

**Issue by strabbit** [SmokeMonsterPacks/Super-NT-Jailbreak#54]
**REQUESTED FEATURE**
Add an option to the menu to enable HDMI CEC auto-switching.

**REASON**
So that upon powering on the Super NT the television automatically turns on (if it wasn't previously) and switches to the correct source.

**Comment by CoolMatty** [comment]
Also, additionally, this would allow home theater receivers to recognize it and present it as a special input, drastically improving usability with such equipment. For example, the PS4 will appear as "Playstation 4" on the input switcher, instead of requiring you to go to the receiver then change receiver inputs.

**Comment by SmokeMonsterPacks** [comment]
The CEC line in the SNT isn't connected, so this won't be possible.
