### ISSUE TITLE
Glitches: Chrono Trigger MSU1 (Hack) Menu Flicker

### ISSUE THREAD

**Issue by SmokeMonsterPacks** [SmokeMonsterPacks/Super-NT-Jailbreak#66]
One frame of black flickering in Chrono Trigger MSU1 Character Menus.
Video of issue: https://clips.twitch.tv/ClumsySullenTortoiseOSfrog

## Steps to reproduce the problem
Move up/down in the character's menu

## ROM name and hash value
Chrono Trigger Symphony (Blake Robinson)
chrono_msu1.sfc
SHA-1 ef611721787f0984df1e4b6690de530df18dc072

## firmware version and SD card model
- Jailbreak firmware version: v6.5

First noticed by qwertymodo in a [Twitch](https://www.twitch.tv/qwertymodo) stream.

**Comment by SmokeMonsterPacks** [comment]
Closing until verified. I'll reopen it if it can be recreated.

**Comment by frederic-mahe** [comment]
Maybe we are more likely to get a confirmation of the bug if the issue remains opened?

**Comment by SmokeMonsterPacks** [comment]
Kev has a fix for Chrono Trigger coming in the next official firmware update.

**Comment by SmokeMonsterPacks** [comment]
Closed until someone tests in JB v6.6. Please comment if it needs to be re-opened.

**Comment by qwertymodo** [comment]
Just chiming in to say that the issue is a confirmed bug in the MSU-1 hack that is exacerbated by the SD2SNES in-game hooks (so you can reduce the issue quite a bit by disabling those).  I've further reduced the issue in recent versions of the MSU-1 patch.  It probably won't be able to be eliminated entirely, but I should be able to reduce it to the point where only a couple of scanlines at the top of the screen flicker, rather than the really bad full-screen issue that currently exists in certain areas with the in-game hooks enabled.
