### ISSUE TITLE
hq scalers changing color pallet

### ISSUE THREAD

**Issue by masterninjah** [SmokeMonsterPacks/Super-NT-Jailbreak#78]
the hq2-4x scaler settings slightly change the color pallet.  the scale 2-3x leaves the colors the same as no scalers on.  

this happens on both real carts and roms

jailbreak firmware 6.5

**Comment by leodsgaming** [comment]
This is a known issue, it's related to the fact this filters require a change in the color thing, that I don't know how it's called, and it's unfixable, or at least a really hard fix, because of the nature of the scaler.

But it's a official firmware issue, and KEvtris himself is fully aware of the issue and exactly how it works.

**Comment by SmokeMonsterPacks** [comment]
I'll close this then since Kev is aware of it. Thanks @masterninjah & @leodsgaming
