### ISSUE TITLE
Improvement: Super Gameboy optimized scaling option

### ISSUE THREAD

**Issue by kylophone** [SmokeMonsterPacks/Super-NT-Jailbreak#94]
I'd love to see an "overscan" function on the Super NT.  This would be hugely useful for scaling Super Gameboy games up to fill the screen. This would be similar to what folks have been doing with the Framemeister/OSSC.

**Comment by Bits-n-Stuff** [comment]
Perhaps the ideal situation here wouldn't be just an overscan option but to have specific Super Gameboy 1 & 2 options? Perhaps something along the lines of these?
Increasing the integer scaling to 7x. (I know it's still outputting it as a SNES game so that may not even be possible.)
Is there a way to remove the stuttering that you get ever few seconds? Perhaps something akin to the frame buffer modes used for SNES games?

**Comment by SmokeMonsterPacks** [comment]
Closing to focus on bugs. This issue will still be publicly accessible.
